export enum SystemErrors {
  GroupNotFound = "GroupNotFound",
  NotMemberOfGroup = "NOT_MEMBER_OF_GROUP",
  UserNotFound = "UserNotFound",
  TargetBlockedYou = "TARGET_BLOCKED_YOU",
  TargetIsBlocked = "TARGET_IS_BLOCKED",
  DevicesOutOfSync = "DEVICES_OUT_OF_SYNC",
  IncorrectSenderKeyVersion = "INCORRECT_SENDER_KEY_VERSION",
  TargetNotMemberOfGroup = "TARGET_NOT_MEMBER_OF_GROUP",
  CannotDeleteThisDevice="CANNOT_DELETE_THIS_DEVICE",
  FileAlreadyUploaded = "FILE_ALREADY_UPLOADED",
  InvalidCredentials = "INVALID_CREDENTIALS",
  InvalidToken = "INVALID_TOKEN",
  TokenExpired = "TOKEN_EXPIRED",
  YouCantRegisterOnNewDevice="DEVICE_LIMIT_EXCEEDED",
  WrongRegistrationOTP = "WrongRegistrationOTP",
  CannotSendOtp = "CANNOT_SEND_OTP",
}
