import { PERMISSIONS } from "react-native-permissions";
import { isAndroid, isIOS } from "../utils/platform";

const MICROPHONE_PERMISSIONS = {
  MICROPHONE:
    isIOS()
      ? PERMISSIONS.IOS.MICROPHONE
      : PERMISSIONS.ANDROID.RECORD_AUDIO,
};

const CAMERA_PERMISSIONS = {
  CAMERA:
    isIOS()
      ? PERMISSIONS.IOS.CAMERA
      : PERMISSIONS.ANDROID.CAMERA,
};

const CONTACTS_PERMISSIONS = {
  CONTACTS:
    isIOS()
      ? PERMISSIONS.IOS.CONTACTS
      : PERMISSIONS.ANDROID.READ_CONTACTS,
};

const LOCATION_PERMISSIONS = {
  LOCATION:
    isIOS()
      ? PERMISSIONS.IOS.LOCATION_WHEN_IN_USE
      : PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
};

const STORAGE_PERMISSIONS = {
  STORAGE:
    isAndroid()
      ? PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE :
      PERMISSIONS.IOS.PHOTO_LIBRARY
}


const WRITE_EXTERNAL_STORAGE_PERMISSIONS = {
  STORAGE:
    isAndroid()
      ? PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE :
        PERMISSIONS.IOS.PHOTO_LIBRARY
}

const READ_PHONE_NUMBERS_PERMISSIONS = {
  READ_PHONE_NUMBERS:PERMISSIONS.ANDROID.READ_PHONE_NUMBERS
}

const READ_PHONE_STATE_PERMISSIONS = {
  READ_PHONE_STATE:PERMISSIONS.ANDROID.READ_PHONE_STATE
}

const NOTIFICATION_PERMISSIONS = {
  NOTIFICATION: PERMISSIONS.ANDROID.POST_NOTIFICATIONS,
}

const DevicePermissions = {
  CAMERA: CAMERA_PERMISSIONS.CAMERA,
  NOTIFICATION:NOTIFICATION_PERMISSIONS.NOTIFICATION,
  MICROPHONE: MICROPHONE_PERMISSIONS.MICROPHONE,
  CONTACTS: CONTACTS_PERMISSIONS.CONTACTS,
  LOCATION: LOCATION_PERMISSIONS.LOCATION,
  STORAGE: STORAGE_PERMISSIONS.STORAGE,
  WRITE_STORAGE: WRITE_EXTERNAL_STORAGE_PERMISSIONS.STORAGE,
  READ_PHONE_NUMBERS:READ_PHONE_NUMBERS_PERMISSIONS.READ_PHONE_NUMBERS,
  READ_PHONE_STATE:READ_PHONE_STATE_PERMISSIONS.READ_PHONE_STATE
};

export default DevicePermissions;
